name: molsysviewer@uibcdf_3.12
channels:
  - conda-forge
dependencies:
  - python=3.12
  - nodejs>=18
  - jupyterlab>=4
  - ipywidgets
  - anywidget
  - watchdog        # autoreload para el desarrollo en JS (Ãºtil si usas vite)
  - python-build           # para empaquetar el paquete Python
  - pytest          # para tests
  - black           # formateo
  - flake8          # linting
